<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\..\src\Modules\TouchFish.Modules.BossKey.Core\TouchFish.Modules.BossKey.Core.csproj" />
    <ProjectReference Include="..\..\src\Modules\TouchFish.Modules.Reader.Core\TouchFish.Modules.Reader.Core.csproj" />
    <ProjectReference Include="..\..\src\TouchFish.Contracts\TouchFish.Contracts.csproj" />
  </ItemGroup>
</Project>
