<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>TouchFish.Modules.Browser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Web.WebView2" />
    <PackageDownload Include="Microsoft.Windows.CsWinRT" Version="[1.6.5]" />
    <PackageDownload Include="Microsoft.Windows.SDK.NET.Ref" Version="[10.0.17763.17]" />
    <ProjectReference Include="..\..\TouchFish.Contracts\TouchFish.Contracts.csproj" />
    <ProjectReference Include="..\..\TouchFish.UI.FloatingWidgets\TouchFish.UI.FloatingWidgets.csproj" />
    <Reference Include="Microsoft.Windows.SDK.NET"
               HintPath="$(NuGetPackageRoot)microsoft.windows.sdk.net.ref/10.0.17763.17/lib/Microsoft.Windows.SDK.NET.dll"
               Private="true" />
    <Reference Include="WinRT.Runtime"
               HintPath="$(NuGetPackageRoot)microsoft.windows.cswinrt/1.6.5/lib/net5.0/WinRT.Runtime.dll"
               Private="true" />
  </ItemGroup>
</Project>
